add
aindrajaya/init pull request #11
Opened 2022-03-14 13:13 UTC by AhmadRafly23

2022-03-15 12:22 UTC, aindrajaya requested changes

2022-03-15 12:22 UTC, aindrajaya commented on ahmadrafly/write.js
> +fs.writeFile("write.txt", isiKonten, function (error) {
Write file nya buat file html ya

2022-03-15 12:22 UTC, aindrajaya commented on ahmadrafly/write.js
> +const isiKonten = "Learn Node Js";
Ini juga, isi konten ganti aja dengan tulisan di file html

2022-03-15 12:39 UTC, AhmadRafly23 commented on ahmadrafly/write.js
> +fs.writeFile("write.txt", isiKonten, function (error) {
sudah mas

2022-03-16 10:08 UTC, aindrajaya reviewed
Done!

2022-03-16 10:08 UTC, closed without merging